name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.11', '1.12' ]
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: |
          go mod download
          go test -race -coverprofile=coverage.txt -covermode=atomic
